spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/book-store-manager?createDatabaseIfNotExist=true
    username: root
    password: root*+77
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

